catalog:
  '@nuxt/test-utils': ^3.17.2
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/vue': ^8.1.0
  '@vitest/coverage-v8': 3.1.1
  '@vue/test-utils': ^2.4.6
  happy-dom: ^17.4.4
  vitest: ^3.1.1
catalogs:
  cli:
    '@antfu/eslint-config': ^4.11.0
    eslint: ^9.23.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.2
    vue-tsc: ^2.2.8
  nuxt:
    '@nuxt/devtools': ^2.3.2
    '@nuxt/eslint': ^1.2.0
    '@nuxtjs/color-mode': ^3.5.2
    nuxt: ^3.16.1
  prod:
    '@provetcloud/css': ^1.1.0
    '@provetcloud/themes': ^1.0.0
    '@provetcloud/web-components': ^1.3.3
    '@provetcloud/web-components-vue-types': ^1.3.3
    '@tailwindcss/vite': ^4.0.17
    '@vee-validate/nuxt': ^4.15.0
    '@vee-validate/zod': ^4.15.0
    tailwindcss: ^4.0.17
    validator: ^13.15.0
    vee-validate: ^4.15.0
    vue: ^3.5.13
    zod: ^3.24.2
  testing:
    '@axe-core/playwright': ^4.10.1
    '@playwright/test': ^1.51.1
  types:
    '@types/node': ^22.13.14
    '@types/validator': ^13.12.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
