catalog:
  '@antfu/eslint-config': ^4.11.0
  '@axe-core/playwright': ^4.10.1
  '@nuxt/devtools': ^2.3.2
  '@nuxt/eslint': ^1.2.0
  '@nuxtjs/color-mode': ^3.5.2
  '@playwright/test': ^1.51.1
  '@provetcloud/css': ^1.1.0
  '@provetcloud/themes': ^1.0.0
  '@provetcloud/web-components': ^1.3.3
  '@provetcloud/web-components-vue-types': ^1.3.3
  '@tailwindcss/vite': ^4.0.17
  '@types/node': ^22.13.14
  '@types/validator': ^13.12.3
  '@vee-validate/nuxt': ^4.15.0
  '@vee-validate/zod': ^4.15.0
  eslint: ^9.23.0
  eslint-plugin-format: ^1.0.1
  nuxt: ^3.16.1
  tailwindcss: ^4.0.17
  typescript: ^5.8.2
  validator: ^13.15.0
  vee-validate: ^4.15.0
  vue: ^3.5.13
  vue-tsc: ^2.2.8
  zod: ^3.24.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
